// Autogenerated from Pigeon (v20.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace sms_otp_autofill {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class SmsOtpAutoFillApi;
  friend class SmsOtpAutoFillFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class AutofillStrategy {
  auto = 0,
  retriever = 1,
  consent = 2
};

// Generated class from Pigeon that represents data sent in messages.
class DiagnosticReport {
 public:
  // Constructs an object setting all non-nullable fields.
  DiagnosticReport();

  // Constructs an object setting all fields.
  explicit DiagnosticReport(
    const bool* is_play_services_available,
    const bool* is_retriever_available,
    const bool* is_user_consent_available,
    const std::string* app_signature,
    const bool* is_receiver_registered);

  const bool* is_play_services_available() const;
  void set_is_play_services_available(const bool* value_arg);
  void set_is_play_services_available(bool value_arg);

  const bool* is_retriever_available() const;
  void set_is_retriever_available(const bool* value_arg);
  void set_is_retriever_available(bool value_arg);

  const bool* is_user_consent_available() const;
  void set_is_user_consent_available(const bool* value_arg);
  void set_is_user_consent_available(bool value_arg);

  const std::string* app_signature() const;
  void set_app_signature(const std::string_view* value_arg);
  void set_app_signature(std::string_view value_arg);

  const bool* is_receiver_registered() const;
  void set_is_receiver_registered(const bool* value_arg);
  void set_is_receiver_registered(bool value_arg);


 private:
  static DiagnosticReport FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class SmsOtpAutoFillApi;
  friend class SmsOtpAutoFillFlutterApi;
  friend class PigeonCodecSerializer;
  std::optional<bool> is_play_services_available_;
  std::optional<bool> is_retriever_available_;
  std::optional<bool> is_user_consent_available_;
  std::optional<std::string> app_signature_;
  std::optional<bool> is_receiver_registered_;

};

class PigeonCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonCodecSerializer();
  inline static PigeonCodecSerializer& GetInstance() {
    static PigeonCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class SmsOtpAutoFillApi {
 public:
  SmsOtpAutoFillApi(const SmsOtpAutoFillApi&) = delete;
  SmsOtpAutoFillApi& operator=(const SmsOtpAutoFillApi&) = delete;
  virtual ~SmsOtpAutoFillApi() {}
  virtual void RequestPhoneHint(std::function<void(ErrorOr<std::optional<std::string>> reply)> result) = 0;
  virtual std::optional<FlutterError> ListenForCode(
    const std::string& regex,
    const AutofillStrategy& strategy,
    const std::string* sender_phone_number) = 0;
  virtual std::optional<FlutterError> UnregisterListener() = 0;
  virtual ErrorOr<std::string> GetAppSignature() = 0;
  virtual ErrorOr<DiagnosticReport> GetDiagnostics() = 0;

  // The codec used by SmsOtpAutoFillApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `SmsOtpAutoFillApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    SmsOtpAutoFillApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    SmsOtpAutoFillApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  SmsOtpAutoFillApi() = default;

};
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class SmsOtpAutoFillFlutterApi {
 public:
  SmsOtpAutoFillFlutterApi(flutter::BinaryMessenger* binary_messenger);
  SmsOtpAutoFillFlutterApi(
    flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const flutter::StandardMessageCodec& GetCodec();
  void OnSmsReceived(
    const std::string& code,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnTimeout(
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnError(
    const std::string& error_code,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);

 private:
  flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace sms_otp_autofill
#endif  // PIGEON_MESSAGES_G_H_
