// Autogenerated from Pigeon (v20.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace sms_otp_autofill {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
    return FlutterError(
        "channel-error",
        "Unable to establish connection on channel: '" + channel_name + "'.",
        EncodableValue(""));
}

// DiagnosticReport

DiagnosticReport::DiagnosticReport() {}

DiagnosticReport::DiagnosticReport(
  const bool* is_play_services_available,
  const bool* is_retriever_available,
  const bool* is_user_consent_available,
  const std::string* app_signature,
  const bool* is_receiver_registered)
 : is_play_services_available_(is_play_services_available ? std::optional<bool>(*is_play_services_available) : std::nullopt),
    is_retriever_available_(is_retriever_available ? std::optional<bool>(*is_retriever_available) : std::nullopt),
    is_user_consent_available_(is_user_consent_available ? std::optional<bool>(*is_user_consent_available) : std::nullopt),
    app_signature_(app_signature ? std::optional<std::string>(*app_signature) : std::nullopt),
    is_receiver_registered_(is_receiver_registered ? std::optional<bool>(*is_receiver_registered) : std::nullopt) {}

const bool* DiagnosticReport::is_play_services_available() const {
  return is_play_services_available_ ? &(*is_play_services_available_) : nullptr;
}

void DiagnosticReport::set_is_play_services_available(const bool* value_arg) {
  is_play_services_available_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void DiagnosticReport::set_is_play_services_available(bool value_arg) {
  is_play_services_available_ = value_arg;
}


const bool* DiagnosticReport::is_retriever_available() const {
  return is_retriever_available_ ? &(*is_retriever_available_) : nullptr;
}

void DiagnosticReport::set_is_retriever_available(const bool* value_arg) {
  is_retriever_available_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void DiagnosticReport::set_is_retriever_available(bool value_arg) {
  is_retriever_available_ = value_arg;
}


const bool* DiagnosticReport::is_user_consent_available() const {
  return is_user_consent_available_ ? &(*is_user_consent_available_) : nullptr;
}

void DiagnosticReport::set_is_user_consent_available(const bool* value_arg) {
  is_user_consent_available_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void DiagnosticReport::set_is_user_consent_available(bool value_arg) {
  is_user_consent_available_ = value_arg;
}


const std::string* DiagnosticReport::app_signature() const {
  return app_signature_ ? &(*app_signature_) : nullptr;
}

void DiagnosticReport::set_app_signature(const std::string_view* value_arg) {
  app_signature_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DiagnosticReport::set_app_signature(std::string_view value_arg) {
  app_signature_ = value_arg;
}


const bool* DiagnosticReport::is_receiver_registered() const {
  return is_receiver_registered_ ? &(*is_receiver_registered_) : nullptr;
}

void DiagnosticReport::set_is_receiver_registered(const bool* value_arg) {
  is_receiver_registered_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void DiagnosticReport::set_is_receiver_registered(bool value_arg) {
  is_receiver_registered_ = value_arg;
}


EncodableList DiagnosticReport::ToEncodableList() const {
  EncodableList list;
  list.reserve(5);
  list.push_back(is_play_services_available_ ? EncodableValue(*is_play_services_available_) : EncodableValue());
  list.push_back(is_retriever_available_ ? EncodableValue(*is_retriever_available_) : EncodableValue());
  list.push_back(is_user_consent_available_ ? EncodableValue(*is_user_consent_available_) : EncodableValue());
  list.push_back(app_signature_ ? EncodableValue(*app_signature_) : EncodableValue());
  list.push_back(is_receiver_registered_ ? EncodableValue(*is_receiver_registered_) : EncodableValue());
  return list;
}

DiagnosticReport DiagnosticReport::FromEncodableList(const EncodableList& list) {
  DiagnosticReport decoded;
  auto& encodable_is_play_services_available = list[0];
  if (!encodable_is_play_services_available.IsNull()) {
    decoded.set_is_play_services_available(std::get<bool>(encodable_is_play_services_available));
  }
  auto& encodable_is_retriever_available = list[1];
  if (!encodable_is_retriever_available.IsNull()) {
    decoded.set_is_retriever_available(std::get<bool>(encodable_is_retriever_available));
  }
  auto& encodable_is_user_consent_available = list[2];
  if (!encodable_is_user_consent_available.IsNull()) {
    decoded.set_is_user_consent_available(std::get<bool>(encodable_is_user_consent_available));
  }
  auto& encodable_app_signature = list[3];
  if (!encodable_app_signature.IsNull()) {
    decoded.set_app_signature(std::get<std::string>(encodable_app_signature));
  }
  auto& encodable_is_receiver_registered = list[4];
  if (!encodable_is_receiver_registered.IsNull()) {
    decoded.set_is_receiver_registered(std::get<bool>(encodable_is_receiver_registered));
  }
  return decoded;
}


PigeonCodecSerializer::PigeonCodecSerializer() {}

EncodableValue PigeonCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129:
      return CustomEncodableValue(DiagnosticReport::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 130:
      {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<AutofillStrategy>(enum_arg_value));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(DiagnosticReport)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<DiagnosticReport>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(AutofillStrategy)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<AutofillStrategy>(*custom_value))), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by SmsOtpAutoFillApi.
const flutter::StandardMessageCodec& SmsOtpAutoFillApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonCodecSerializer::GetInstance());
}

// Sets up an instance of `SmsOtpAutoFillApi` to handle messages through the `binary_messenger`.
void SmsOtpAutoFillApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  SmsOtpAutoFillApi* api) {
  SmsOtpAutoFillApi::SetUp(binary_messenger, api, "");
}

void SmsOtpAutoFillApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  SmsOtpAutoFillApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillApi.requestPhoneHint" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->RequestPhoneHint([reply](ErrorOr<std::optional<std::string>>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            auto output_optional = std::move(output).TakeValue();
            if (output_optional) {
              wrapped.push_back(EncodableValue(std::move(output_optional).value()));
            } else {
              wrapped.push_back(EncodableValue());
            }
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillApi.listenForCode" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_regex_arg = args.at(0);
          if (encodable_regex_arg.IsNull()) {
            reply(WrapError("regex_arg unexpectedly null."));
            return;
          }
          const auto& regex_arg = std::get<std::string>(encodable_regex_arg);
          const auto& encodable_strategy_arg = args.at(1);
          if (encodable_strategy_arg.IsNull()) {
            reply(WrapError("strategy_arg unexpectedly null."));
            return;
          }
          const auto& strategy_arg = std::any_cast<const AutofillStrategy&>(std::get<CustomEncodableValue>(encodable_strategy_arg));
          const auto& encodable_sender_phone_number_arg = args.at(2);
          const auto* sender_phone_number_arg = std::get_if<std::string>(&encodable_sender_phone_number_arg);
          std::optional<FlutterError> output = api->ListenForCode(regex_arg, strategy_arg, sender_phone_number_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillApi.unregisterListener" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->UnregisterListener();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillApi.getAppSignature" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<std::string> output = api->GetAppSignature();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillApi.getDiagnostics" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<DiagnosticReport> output = api->GetDiagnostics();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue SmsOtpAutoFillApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue SmsOtpAutoFillApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
SmsOtpAutoFillFlutterApi::SmsOtpAutoFillFlutterApi(flutter::BinaryMessenger* binary_messenger)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_("") {}

SmsOtpAutoFillFlutterApi::SmsOtpAutoFillFlutterApi(
  flutter::BinaryMessenger* binary_messenger,
  const std::string& message_channel_suffix)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_(message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "") {}

const flutter::StandardMessageCodec& SmsOtpAutoFillFlutterApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonCodecSerializer::GetInstance());
}

void SmsOtpAutoFillFlutterApi::OnSmsReceived(
  const std::string& code_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillFlutterApi.onSmsReceived" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(code_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void SmsOtpAutoFillFlutterApi::OnTimeout(
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillFlutterApi.onTimeout" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue();
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void SmsOtpAutoFillFlutterApi::OnError(
  const std::string& error_code_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillFlutterApi.onError" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(error_code_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

}  // namespace sms_otp_autofill
