// Autogenerated from Pigeon (v20.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, AutofillStrategy) {
  AutofillStrategyAuto = 0,
  AutofillStrategyRetriever = 1,
  AutofillStrategyConsent = 2,
};

/// Wrapper for AutofillStrategy to allow for nullability.
@interface AutofillStrategyBox : NSObject
@property(nonatomic, assign) AutofillStrategy value;
- (instancetype)initWithValue:(AutofillStrategy)value;
@end

@class DiagnosticReport;

@interface DiagnosticReport : NSObject
+ (instancetype)makeWithIsPlayServicesAvailable:(nullable NSNumber *)isPlayServicesAvailable
    isRetrieverAvailable:(nullable NSNumber *)isRetrieverAvailable
    isUserConsentAvailable:(nullable NSNumber *)isUserConsentAvailable
    appSignature:(nullable NSString *)appSignature
    isReceiverRegistered:(nullable NSNumber *)isReceiverRegistered;
@property(nonatomic, strong, nullable) NSNumber * isPlayServicesAvailable;
@property(nonatomic, strong, nullable) NSNumber * isRetrieverAvailable;
@property(nonatomic, strong, nullable) NSNumber * isUserConsentAvailable;
@property(nonatomic, copy, nullable) NSString * appSignature;
@property(nonatomic, strong, nullable) NSNumber * isReceiverRegistered;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *nullGetMessagesCodec(void);

@protocol SmsOtpAutoFillApi
- (void)requestPhoneHintWithCompletion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
- (void)listenForCodeRegex:(NSString *)regex strategy:(AutofillStrategy)strategy senderPhoneNumber:(nullable NSString *)senderPhoneNumber error:(FlutterError *_Nullable *_Nonnull)error;
- (void)unregisterListenerWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getAppSignatureWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable DiagnosticReport *)getDiagnosticsWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpSmsOtpAutoFillApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<SmsOtpAutoFillApi> *_Nullable api);

extern void SetUpSmsOtpAutoFillApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<SmsOtpAutoFillApi> *_Nullable api, NSString *messageChannelSuffix);


@interface SmsOtpAutoFillFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger messageChannelSuffix:(nullable NSString *)messageChannelSuffix;
- (void)onSmsReceivedCode:(NSString *)code completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onTimeoutWithCompletion:(void (^)(FlutterError *_Nullable))completion;
- (void)onErrorErrorCode:(NSString *)errorCode completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
