// Autogenerated from Pigeon (v20.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "./include/sms_autofill_plus/Messages.g.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static FlutterError *createConnectionError(NSString *channelName) {
  return [FlutterError errorWithCode:@"channel-error" message:[NSString stringWithFormat:@"%@/%@/%@", @"Unable to establish connection on channel: '", channelName, @"'."] details:@""];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@implementation AutofillStrategyBox
- (instancetype)initWithValue:(AutofillStrategy)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@interface DiagnosticReport ()
+ (DiagnosticReport *)fromList:(NSArray<id> *)list;
+ (nullable DiagnosticReport *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation DiagnosticReport
+ (instancetype)makeWithIsPlayServicesAvailable:(nullable NSNumber *)isPlayServicesAvailable
    isRetrieverAvailable:(nullable NSNumber *)isRetrieverAvailable
    isUserConsentAvailable:(nullable NSNumber *)isUserConsentAvailable
    appSignature:(nullable NSString *)appSignature
    isReceiverRegistered:(nullable NSNumber *)isReceiverRegistered {
  DiagnosticReport* pigeonResult = [[DiagnosticReport alloc] init];
  pigeonResult.isPlayServicesAvailable = isPlayServicesAvailable;
  pigeonResult.isRetrieverAvailable = isRetrieverAvailable;
  pigeonResult.isUserConsentAvailable = isUserConsentAvailable;
  pigeonResult.appSignature = appSignature;
  pigeonResult.isReceiverRegistered = isReceiverRegistered;
  return pigeonResult;
}
+ (DiagnosticReport *)fromList:(NSArray<id> *)list {
  DiagnosticReport *pigeonResult = [[DiagnosticReport alloc] init];
  pigeonResult.isPlayServicesAvailable = GetNullableObjectAtIndex(list, 0);
  pigeonResult.isRetrieverAvailable = GetNullableObjectAtIndex(list, 1);
  pigeonResult.isUserConsentAvailable = GetNullableObjectAtIndex(list, 2);
  pigeonResult.appSignature = GetNullableObjectAtIndex(list, 3);
  pigeonResult.isReceiverRegistered = GetNullableObjectAtIndex(list, 4);
  return pigeonResult;
}
+ (nullable DiagnosticReport *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [DiagnosticReport fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.isPlayServicesAvailable ?: [NSNull null],
    self.isRetrieverAvailable ?: [NSNull null],
    self.isUserConsentAvailable ?: [NSNull null],
    self.appSignature ?: [NSNull null],
    self.isReceiverRegistered ?: [NSNull null],
  ];
}
@end

@interface nullMessagesPigeonCodecReader : FlutterStandardReader
@end
@implementation nullMessagesPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: 
      return [DiagnosticReport fromList:[self readValue]];
    case 130: 
      {
        NSNumber *enumAsNumber = [self readValue];
        return enumAsNumber == nil ? nil : [[AutofillStrategyBox alloc] initWithValue:[enumAsNumber integerValue]];
      }
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface nullMessagesPigeonCodecWriter : FlutterStandardWriter
@end
@implementation nullMessagesPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[DiagnosticReport class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[AutofillStrategyBox class]]) {
    AutofillStrategyBox * box = (AutofillStrategyBox *)value;
    [self writeByte:130];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else {
    [super writeValue:value];
  }
}
@end

@interface nullMessagesPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation nullMessagesPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[nullMessagesPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[nullMessagesPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *nullGetMessagesCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    nullMessagesPigeonCodecReaderWriter *readerWriter = [[nullMessagesPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpSmsOtpAutoFillApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<SmsOtpAutoFillApi> *api) {
  SetUpSmsOtpAutoFillApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpSmsOtpAutoFillApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<SmsOtpAutoFillApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillApi.requestPhoneHint", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(requestPhoneHintWithCompletion:)], @"SmsOtpAutoFillApi api (%@) doesn't respond to @selector(requestPhoneHintWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api requestPhoneHintWithCompletion:^(NSString *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillApi.listenForCode", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(listenForCodeRegex:strategy:senderPhoneNumber:error:)], @"SmsOtpAutoFillApi api (%@) doesn't respond to @selector(listenForCodeRegex:strategy:senderPhoneNumber:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_regex = GetNullableObjectAtIndex(args, 0);
        AutofillStrategyBox *enumBox = GetNullableObjectAtIndex(args, 1);
        AutofillStrategy arg_strategy = enumBox.value;
        NSString *arg_senderPhoneNumber = GetNullableObjectAtIndex(args, 2);
        FlutterError *error;
        [api listenForCodeRegex:arg_regex strategy:arg_strategy senderPhoneNumber:arg_senderPhoneNumber error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillApi.unregisterListener", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(unregisterListenerWithError:)], @"SmsOtpAutoFillApi api (%@) doesn't respond to @selector(unregisterListenerWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api unregisterListenerWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillApi.getAppSignature", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getAppSignatureWithError:)], @"SmsOtpAutoFillApi api (%@) doesn't respond to @selector(getAppSignatureWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSString *output = [api getAppSignatureWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillApi.getDiagnostics", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getDiagnosticsWithError:)], @"SmsOtpAutoFillApi api (%@) doesn't respond to @selector(getDiagnosticsWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        DiagnosticReport *output = [api getDiagnosticsWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface SmsOtpAutoFillFlutterApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@property(nonatomic, strong) NSString *messageChannelSuffix;
@end

@implementation SmsOtpAutoFillFlutterApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  return [self initWithBinaryMessenger:binaryMessenger messageChannelSuffix:@""];
}
- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger messageChannelSuffix:(nullable NSString*)messageChannelSuffix{
  self = [self init];
  if (self) {
    _binaryMessenger = binaryMessenger;
    _messageChannelSuffix = [messageChannelSuffix length] == 0 ? @"" : [NSString stringWithFormat: @".%@", messageChannelSuffix];
  }
  return self;
}
- (void)onSmsReceivedCode:(NSString *)arg_code completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillFlutterApi.onSmsReceived", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetMessagesCodec()];
  [channel sendMessage:@[arg_code ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onTimeoutWithCompletion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillFlutterApi.onTimeout", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetMessagesCodec()];
  [channel sendMessage:nil reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onErrorErrorCode:(NSString *)arg_errorCode completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillFlutterApi.onError", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:nullGetMessagesCodec()];
  [channel sendMessage:@[arg_errorCode ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
@end

