// Autogenerated from Pigeon (v20.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum AutofillStrategy: Int {
  case auto = 0
  case retriever = 1
  case consent = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct DiagnosticReport {
  var isPlayServicesAvailable: Bool? = nil
  var isRetrieverAvailable: Bool? = nil
  var isUserConsentAvailable: Bool? = nil
  var appSignature: String? = nil
  var isReceiverRegistered: Bool? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> DiagnosticReport? {
    let isPlayServicesAvailable: Bool? = nilOrValue(__pigeon_list[0])
    let isRetrieverAvailable: Bool? = nilOrValue(__pigeon_list[1])
    let isUserConsentAvailable: Bool? = nilOrValue(__pigeon_list[2])
    let appSignature: String? = nilOrValue(__pigeon_list[3])
    let isReceiverRegistered: Bool? = nilOrValue(__pigeon_list[4])

    return DiagnosticReport(
      isPlayServicesAvailable: isPlayServicesAvailable,
      isRetrieverAvailable: isRetrieverAvailable,
      isUserConsentAvailable: isUserConsentAvailable,
      appSignature: appSignature,
      isReceiverRegistered: isReceiverRegistered
    )
  }
  func toList() -> [Any?] {
    return [
      isPlayServicesAvailable,
      isRetrieverAvailable,
      isUserConsentAvailable,
      appSignature,
      isReceiverRegistered,
    ]
  }
}
private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return DiagnosticReport.fromList(self.readValue() as! [Any?])
    case 130:
      var enumResult: AutofillStrategy? = nil
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as? Int)
      if let enumResultAsInt = enumResultAsInt {
        enumResult = AutofillStrategy(rawValue: enumResultAsInt)
      }
      return enumResult
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DiagnosticReport {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? AutofillStrategy {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SmsOtpAutoFillApi {
  func requestPhoneHint(completion: @escaping (Result<String?, Error>) -> Void)
  func listenForCode(regex: String, strategy: AutofillStrategy, senderPhoneNumber: String?) throws
  func unregisterListener() throws
  func getAppSignature() throws -> String
  func getDiagnostics() throws -> DiagnosticReport
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SmsOtpAutoFillApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `SmsOtpAutoFillApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SmsOtpAutoFillApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let requestPhoneHintChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillApi.requestPhoneHint\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPhoneHintChannel.setMessageHandler { _, reply in
        api.requestPhoneHint { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPhoneHintChannel.setMessageHandler(nil)
    }
    let listenForCodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillApi.listenForCode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listenForCodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let regexArg = args[0] as! String
        let strategyArg = args[1] as! AutofillStrategy
        let senderPhoneNumberArg: String? = nilOrValue(args[2])
        do {
          try api.listenForCode(regex: regexArg, strategy: strategyArg, senderPhoneNumber: senderPhoneNumberArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      listenForCodeChannel.setMessageHandler(nil)
    }
    let unregisterListenerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillApi.unregisterListener\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unregisterListenerChannel.setMessageHandler { _, reply in
        do {
          try api.unregisterListener()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      unregisterListenerChannel.setMessageHandler(nil)
    }
    let getAppSignatureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillApi.getAppSignature\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAppSignatureChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAppSignature()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAppSignatureChannel.setMessageHandler(nil)
    }
    let getDiagnosticsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillApi.getDiagnostics\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDiagnosticsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDiagnostics()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDiagnosticsChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol SmsOtpAutoFillFlutterApiProtocol {
  func onSmsReceived(code codeArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onTimeout(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onError(errorCode errorCodeArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class SmsOtpAutoFillFlutterApi: SmsOtpAutoFillFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onSmsReceived(code codeArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillFlutterApi.onSmsReceived\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([codeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onTimeout(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillFlutterApi.onTimeout\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onError(errorCode errorCodeArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.sms_otp_autofill.SmsOtpAutoFillFlutterApi.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorCodeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
